# Generated by Django 5.1.3 on 2024-11-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_accommodation_no_of_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='review_date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
