# Generated by Django 5.1.3 on 2024-11-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_accommodation_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='review_date',
        ),
    ]
