# Generated by Django 5.1.3 on 2024-12-01 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_rename_accomodation_reservation_accommodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Price는 음수가 아니여야 합니다.')]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
